### ISSUE TITLE
s3 operations should exclude localPath and use relative mapping instead

### ISSUE THREAD

**Issue by nhumphreys** [edlinklater/silverstripe-cloudassets-s3#1]
the current implementation assumes the resources to live within the `bucket/mapping` structure, however they are only put into S3 with their relativeLink 

This works fine for basic upload and use operations, but seemingly breaks for rename and deletes.

Needs testing, but mostly addressed in: https://github.com/nhumphreys/silverstripe-cloudassets-s3/commit/814e25d69f89ff8e86ca8661d4ddfc59146184f9

**Comment by edlinklater** [comment]
Thanks @nhumphreys. I'll give it a bit of a test and merge if it seems OK :smile_cat:
