### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by xmarkclx** [edlinklater/silverstripe-cloudassets-s3#5]
Hi Ed!

I can't seem to get the module to work and want to find out why it doesn't

Can you provide some sort of test build task so people can see if it can connect properly to the S3 server?

Thanks.

**Comment by edlinklater** [comment]
Hi @xmarkclx,

I haven't touched this module for a long time, so it is entirely possible it isn't working any longer. I've reserved some time on Friday to have a look at it.
