### ISSUE TITLE
Issue when i trying to upload image via UploadField

### ISSUE THREAD

**Issue by doniz** [edlinklater/silverstripe-cloudassets-s3#9]
I'am installed packages via composer, framework version is 3.2.1, so when i trying to upload an image via UploadField i'am getting this error:

``` shell
Object->__call(): the method 'parent' does not exist on 'Image'
```

any ideas where it comes from?

**Comment by JZubero** [comment]
Hey @Doniz, I had the same problem. Make sure you invoke CloudImage instead of Image (also in relation definitions). That did it for me.
